# Generated by Django 4.2 on 2026-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='gst_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
