# Generated by Django 4.2 on 2026-03-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_suppliers_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
