# Generated by Django 4.2 on 2026-03-06 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('dashboard', '0004_alter_suppliers_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.address')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.addresstype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.suppliers')),
            ],
            options={
                'unique_together': {('supplier', 'address')},
            },
        ),
    ]
