# Generated by Django 4.2 on 2026-03-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_supplieraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SupplierAddress',
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
