# Generated by Django 4.2 on 2026-03-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='User/'),
        ),
    ]

