# Generated by Django 4.2 on 2026-03-06 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('accounts', '0004_remove_staff_profile_image_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAddress',
            fields=[
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.address')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.addresstype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.staff')),
            ],
            options={
                'unique_together': {('staff', 'address')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.address')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.addresstype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.customer')),
            ],
            options={
                'unique_together': {('customer', 'address')},
            },
        ),
    ]

