# Generated by Django 4.2 on 2026-03-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffaddress_customeraddress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customeraddress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='staffaddress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staffaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='staffaddress',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffAddress',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]

