# Generated by Django 4.2 on 2026-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_customeraddress_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone_number', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('password', models.CharField(
                    db_column='password_hash', max_length=255)),
                ('profile_image', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[
                 ('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
