# Generated by Django 4.2 on 2026-03-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_brand_delete_category_delete_supplieraddress_and_more'),
        ('accounts', '0006_alter_customeraddress_unique_together_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='pincode',
        ),
        migrations.DeleteModel(
            name='AddressType',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='city',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Pincode',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]

