# Generated by Django 4.2 on 2026-03-10 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0002_remove_address_pincode_delete_addresstype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('pincode_id', models.AutoField(primary_key=True, serialize=False)),
                ('pincode', models.IntegerField()),
                ('area_name', models.CharField(max_length=30)),
                ('city', models.CharField(default='Ahmedabad', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
                ('is_primary', models.BooleanField(default=False)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.pincode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
